parameters:
    codemaster.mailup.class: Codemaster\Bundle\MailupBundle\Webservice\Rest

services:
#    mailup.example:
#        class: Codemaster\Bundle\MailupBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    codemaster.mailup:
        class: %codemaster.mailup.class%
        arguments:
            - @guzzle.client.codemaster_mailup
            - @session
            - @logger
            - %mailup_token_secret%
